// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WTW.App.Data;

namespace WTW.App.Data.Migrations
{
    [DbContext(typeof(PolicyContext))]
    [Migration("20191211012438_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WTW.App.Domain.Policy", b =>
                {
                    b.Property<int>("PolicyNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PolicyHolderId");

                    b.HasKey("PolicyNumber");

                    b.HasIndex("PolicyHolderId");

                    b.ToTable("Policies");

                    b.HasData(
                        new { PolicyNumber = 739562, PolicyHolderId = 1 },
                        new { PolicyNumber = 383002, PolicyHolderId = 1 },
                        new { PolicyNumber = 462946, PolicyHolderId = 2 },
                        new { PolicyNumber = 355679, PolicyHolderId = 3 },
                        new { PolicyNumber = 589881, PolicyHolderId = 3 },
                        new { PolicyNumber = 998256, PolicyHolderId = 3 },
                        new { PolicyNumber = 100374, PolicyHolderId = 3 }
                    );
                });

            modelBuilder.Entity("WTW.App.Domain.PolicyHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("Gender");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PolicyHolders");

                    b.HasData(
                        new { Id = 1, Age = 44, Gender = 0, Name = "Dwayne Johnson" },
                        new { Id = 2, Age = 38, Gender = 0, Name = "John Cena" },
                        new { Id = 3, Age = 42, Gender = 1, Name = "Trish Stratus" }
                    );
                });

            modelBuilder.Entity("WTW.App.Domain.Policy", b =>
                {
                    b.HasOne("WTW.App.Domain.PolicyHolder", "PolicyHolder")
                        .WithMany()
                        .HasForeignKey("PolicyHolderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
